version: "3"

networks:
  pg-express:
    external: false

services:
  pg-db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pg-user
      POSTGRES_DB: groceries
      POSTGRES_PASSWORD: pg-password
    networks:
      - pg-express
  pg-express-api:
    image: node:12-alpine
    restart: unless-stopped
    command: sh -c "npm install && npm run start"
    ports:
      - 5000:5000
    working_dir: /pg-express-api
    volumes:
      - ./:/pg-express-api
    depends_on:
      - pg-db
    environment:
      PORT: 5000
      HOST: pg-db
      USER: pg-user
      PASS: pg-password
      DB: groceries
    networks:
      - pg-express



