version: "3"

services:
  pg-db:
    image: postgres
    restart: unless-stopped
    ports:
      5001:5001
    environment:
      POSTGRES_USER: pg-user
      POSTGRES_DB: groceries
      POSTGRES_PASSWORD: pg-password
  pg-express-api:
    image: node:12-alpine
    restart: unless-stopped
    command: sh -c "npm install && npm run start"
    ports:
      - 5000:5000
    working_dir: /pg-express-api
    volumes:
      - ./:/pg-express-api
    depends_on:
      - pg-db
    environment:
      PORT: 5000
      HOST: pg-db
      USER: pg-user
      PASS: pg-password
      DB: groceries
      PGPORT: 5001



